from funcion_scrap_valorjug import Equipos_Transfermarkt

#importamos la funcion creada y le pasamos un diccionariop de links para que itere y se aplique en cada uno de ellos y exporte  a csv con el nombre del pais correspondiente

links_transfer={'Argentina':'https://www.transfermarkt.com.ar/argentina/kader/verein/3437/saison_id/2022/plus/1', 'Brasil': 'https://www.transfermarkt.com.ar/brasil/kader/verein/3439/saison_id/2022/plus/1', 'Belgica': 'https://www.transfermarkt.com.ar/belgica/kader/verein/3382/saison_id/2022/plus/1','Francia':'https://www.transfermarkt.com.ar/francia/kader/verein/3377/saison_id/2022/plus/1', 'Inglaterra': 'https://www.transfermarkt.com.ar/inglaterra/kader/verein/3299/saison_id/2022/plus/1',
'Portugal':'https://www.transfermarkt.com.ar/portugal/kader/verein/3300/saison_id/2022/plus/1', 'España': 'https://www.transfermarkt.com.ar/espana/kader/verein/3375/saison_id/2022/plus/1', 'Paises Bajos':'https://www.transfermarkt.com.ar/paises-bajos/kader/verein/3379/saison_id/2022/plus/1', 'Uruguay': 'https://www.transfermarkt.com.ar/uruguay/kader/verein/3449/saison_id/2022/plus/1', 'Croacia': 'https://www.transfermarkt.com.ar/croacia/kader/verein/3556/saison_id/2022/plus/1', 'Dinamarca': 'https://www.transfermarkt.com.ar/dinamarca/kader/verein/3436/saison_id/2022/plus/1', 'Serbia': 'https://www.transfermarkt.com.ar/serbia/kader/verein/3438/saison_id/2022/plus/1', 'Senegal':'https://www.transfermarkt.com.ar/senegal/kader/verein/3499/saison_id/2022/plus/1', 'Polonia': 'https://www.transfermarkt.com.ar/polonia/kader/verein/3442/saison_id/2022/plus/1', 'Marruecos':'https://www.transfermarkt.com.ar/marruecos/kader/verein/3575/saison_id/2022/plus/1', 'Mexico': 'https://www.transfermarkt.com.ar/mexico/kader/verein/6303/saison_id/2022/plus/1', 'Estados _Unidos': 'https://www.transfermarkt.com.ar/estados-unidos/kader/verein/3505/saison_id/2022/plus/1', 'Ghana':'https://www.transfermarkt.com.ar/ghana/kader/verein/3441/saison_id/2022/plus/1','Suiza':'https://www.transfermarkt.com.ar/suiza/kader/verein/3384/saison_id/2022/plus/1', 'Canada':'https://www.transfermarkt.com.ar/canada/kader/verein/3510/saison_id/2022/plus/1', 'Corea_del_Sur':'https://www.transfermarkt.com.ar/corea-del-sur/kader/verein/3589/saison_id/2022/plus/1','Gales':'https://www.transfermarkt.com.ar/gales/kader/verein/3864/saison_id/2022/plus/1', 'Japon':'https://www.transfermarkt.com.ar/japon/kader/verein/3435/saison_id/2021/plus/1', 'Ecuador':'https://www.transfermarkt.com.ar/ecuador/kader/verein/5750/saison_id/2022/plus/1', 'Camerun': 'https://www.transfermarkt.com.ar/camerun/kader/verein/3434/saison_id/2022/plus/1	', 'Iran': 'https://www.transfermarkt.com.ar/iran/kader/verein/3582/saison_id/2022/plus/1', 'Tunez': 'https://www.transfermarkt.com.ar/tunez/kader/verein/3670/saison_id/2022/plus/1', 'Australia': 'https://www.transfermarkt.com.ar/australia/kader/verein/3433/saison_id/2022/plus/1', 'Arabia_Saudita': 'https://www.transfermarkt.com.ar/arabia-saudita/kader/verein/3807/saison_id/2022/plus/1', 'Qatar': 'https://www.transfermarkt.com.ar/catar/kader/verein/14162/saison_id/2022/plus/1', 'Costa_Rica':'https://www.transfermarkt.com.ar/costa-rica/kader/verein/8497/saison_id/2022/plus/1'}

def selecciones():
    for n,l in links_transfer.items():
        Equipos_Transfermarkt(l).to_csv(f'Data\Equipos\{n}.csv', index= False)

selecciones()