import pandas as pd
from funcion_scrap_equipos import Equipos_fifa

#Se actualiza Scrap unificando todos los equipos en un solo CSV

links_transfer=['https://www.transfermarkt.com.ar/argentina/kader/verein/3437/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/brasil/kader/verein/3439/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/belgica/kader/verein/3382/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/francia/kader/verein/3377/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/inglaterra/kader/verein/3299/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/portugal/kader/verein/3300/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/espana/kader/verein/3375/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/paises-bajos/kader/verein/3379/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/uruguay/kader/verein/3449/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/croacia/kader/verein/3556/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/dinamarca/kader/verein/3436/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/serbia/kader/verein/3438/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/senegal/kader/verein/3499/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/polonia/kader/verein/3442/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/marruecos/kader/verein/3575/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/mexico/kader/verein/6303/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/estados-unidos/kader/verein/3505/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/ghana/kader/verein/3441/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/suiza/kader/verein/3384/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/canada/kader/verein/3510/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/corea-del-sur/kader/verein/3589/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/gales/kader/verein/3864/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/japon/kader/verein/3435/saison_id/2021/plus/1', 'https://www.transfermarkt.com.ar/ecuador/kader/verein/5750/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/camerun/kader/verein/3434/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/iran/kader/verein/3582/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/tunez/kader/verein/3670/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/australia/kader/verein/3433/saison_id/2022/plus/1',  'https://www.transfermarkt.com.ar/arabia-saudita/kader/verein/3807/saison_id/2022/plus/1','https://www.transfermarkt.com.ar/catar/kader/verein/14162/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/costa-rica/kader/verein/8497/saison_id/2022/plus/1', 'https://www.transfermarkt.com.ar/alemania/kader/verein/3262/saison_id/2022/plus/1']

df_equipo= pd.DataFrame(columns=['#','Jugadores','Posicion','Edad','Nacido','Altura','Pie','Partidos con la selección','Goles','Debut','Valor mercado en €'])

for l in links_transfer:
    data=Equipos_fifa(l)
    df_equipo= pd.concat([df_equipo,data],ignore_index=True)
    
df_equipo.to_csv('Data\Equipos\Equipos_Fifa.csv', index=False, encoding="utf-8")
